# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('xingzuo', models.CharField(max_length=20, verbose_name='星座')),
                ('image', models.ImageField(null=True, upload_to='static/upload/goods', verbose_name='图片')),
                ('isActive', models.BooleanField(verbose_name='是否显示')),
            ],
            options={
                'db_table': 'heros',
                'verbose_name_plural': '英雄',
                'verbose_name': '英雄',
            },
        ),
    ]
